[package]
name = "magitulator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gitm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
gix = "0.73.0"
thiserror = "2.0.16"
